Movies API
storres20/M3-react-capstone pull request #1
Opened 2023-01-03 22:28 UTC by storres20

# In this milestone we did the following activities:
- Add "moviesapi" branch
- Set up react app
- Install React Redux, React Router, React Bootstrap
- Set up Redux store and Reducers
- Set up linters
- Add Home, Details, About pages
- Add Searchbar, SearchCat, Navbar and other components
- Add testing files

2023-01-03 23:20 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @storres20,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used the correct workflow.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-03 23:20 UTC, omar-muhamad commented on src/pages/HomePage/HomePage.jsx
> +
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#:~:text=Layout%3A%20composition%20and%20space%20between%20elements.), For the home page, Please make the movies categories shaped in a two-column grid and the background color is staggered like a chessboard to match the given design.

| Given Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/210455527-172e4e9d-4a66-4967-8303-61b010d5730a.png)  | ![image](https://user-images.githubusercontent.com/68796232/210455471-7dfed2b9-52f7-40da-95fc-fdeb7fdcec17.png) |

### ⚠️This is a mobile application, So please focus on the mobile view only and make sure that you follow the given design⚠️

2023-01-03 23:20 UTC, omar-muhamad commented on src/pages/DetailPage/MoviesGrid.jsx
> +            </div>
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#:~:text=Layout%3A%20composition%20and%20space%20between%20elements.), For the details page, please make sure that the back button appears on the left side of the navbar to match the given design.

| Given Design  | Your Design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/68796232/210456632-73dcf624-0efa-4cc2-9f0c-a641e7b22c6e.png)  | ![image](https://user-images.githubusercontent.com/68796232/210456613-9afa2975-094e-42c4-9d5f-0202ff3cc80a.png)  |

2023-01-03 23:20 UTC, omar-muhamad commented on src/tests/AboutPage.test.js
> +});
You only add screenshot tests to your app:

- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#:~:text=Create%20unit%20tests%20for%20pure%20functions%20in%20your%20Redux%20code.), Please add unit tests for pure functions in your Redux code.
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md#:~:text=Create%20integration%20tests%20for%20your%20application%20using%20the%20React%20Testing%20Library), Please add integration tests for your application using the React Testing Library like mocking the connection to the Redux Store.

2023-01-05 15:54 UTC, franclobo approved these changes
Hi @storres20, 

# STATUS: APPROVED 😃 

![gif-good-job-79](https://user-images.githubusercontent.com/58642949/210823419-91a0877f-9639-4a6c-b0f0-361eee60f209.gif)

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

## Highlights

- No linter errors ✔️ 
- Correct Git flow ✔️ 
- Descriptive PR ✔️ 
- Professional README file ✔️ 

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-01-05 23:05 UTC, merged